# Generated by Django 6.0.4 on 2026-04-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Waiting"),
                    ("paid", "Paid"),
                    ("created", "Created"),
                    ("delivery", "Delivery"),
                    ("canceled", "Canceled"),
                ],
                default="created",
                max_length=30,
            ),
        ),
    ]
