# Generated by Django 6.0.2 on 2026-03-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, default='static/Book', null=True, upload_to='static/'),
        ),
    ]
