# Generated by Django 6.0.2 on 2026-03-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_book_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.CharField(blank=True, max_length=30, verbose_name='Book author'),
        ),
    ]
