# Generated by Django 6.0.2 on 2026-03-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.CharField(max_length=30, null=True, verbose_name='Book author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Book Title'),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
